### ISSUE TITLE
Aktualizacja połączenia pomiędzy contenerami

### ISSUE THREAD

**Issue by szoz** [arturgorski14/PackageFinder#1]
Wygląda na to, że połączenie pomiędzy kontenerami działa, bo:
* Po wywołaniu `curl -X GET kibana:5601` z kontenera elasticsearch-cn nie otrzymuję błędu.
* Mogę otworzyć kibanę na `http://localhost:5601` i odczytać jakieś dane w sekcji dev tools.

Odkomentowałem sieć w pliku docker compose i zmieniłem w zmiennych środowiskowych URL. Ważne jest aby były w nich nazwy usług a nie localhost. Docker compose tworzy podsieć i w niej przekierowuje ruch po nazwach usług. Zauważyłem, że taką zmianę trzeba też wykonać w pliku settings.py Django.

Contener djangoapp nie potrzebuje volume. Jeżeli byś dodawał bazę danych SQL to lepiej volume zadeklarować jako "name:/path/" bo wtedy volume nie masz w katalogu projektu i do black i flake8 nie musisz dodawać ignorowania podkatalogu w folderze projektu.

```yml
version: '3.11'

services:
  djangoapp:
    build: .
    container_name: django-app
    depends_on:
      - elasticsearch
    environment:
     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
     - custom-network
    ports:
      - 8000:8000
#    volumes:
#      - .:/app

  elasticsearch:
    container_name: elasticsearch-cn
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
#      - boostrap.memory_lock=true
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    networks:
     - custom-network
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana-cn
    depends_on:
      - elasticsearch
    environment:
     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    image: docker.elastic.co/kibana/kibana:7.17.9
    networks:
     - custom-network
    ports:
      - 5601:5601

networks:
  custom-network:
```
